### ISSUE TITLE
Review and Unify Joint Directions of Rotation

### ISSUE THREAD

**Issue by jgvictores** [roboticslab-uc3m/teo-main#39]
Review Joint Directions of Rotation https://github.com/roboticslab-uc3m/teo-developer-manual/blob/master/appendix/a-teo-diagrams.md#joint-directions-of-rotation then unify

**Comment by rsantos88** [comment]
I found that some directions of rotation are wrong.
Do you want to correct the diagram or the direction in the real robot?

**Comment by rsantos88** [comment]
The signs are ok but, @jmgarciah and me think that the arrows can generate confusin in the Y axis

**Comment by jmgarciah** [comment]
Talking with @smcdiaz and seeing the TEO's hardware, we have found a possible solution. Related with the two saggital motor of the legs, the wires of the gear are different from the rest. 

@jgvictores have given me permission to change the order of the wires and have the same turning sense that the diagram.

**Comment by jmgarciah** [comment]
I have found an image that could be insteresting for a new TEO diagram. And finally understand the joint direction.

![imagen1](https://user-images.githubusercontent.com/16653267/36472652-b7531ca4-16f2-11e8-899e-19b4b4386acd.png)

**Comment by jgvictores** [comment]
Looks nice, could be done with TEO.

I would try to avoid the RPY terminology (Roll is Z in some fields) and stick to ours.

**Comment by jmgarciah** [comment]
I totally agree. It is only an idea. So please, take it as you need

**Comment by RaulFdzbis** [comment]
In my opinion, i think that overlapping of the robot model over the axis, make that image a little overload, and can be confusing.

Maybe a good solution could be to use the simplified model that is used now with the Teo Joint Directions of Rotation but with the perspective in that image, for an easier understanding.

**Comment by jgvictores** [comment]
If anyone could take a picture of TEO in a pose similar to NAO there (same perspective, but arms pointing down), I could give it a shot. Some alpha layer magic should do the trick. :-)

**Comment by David-Estevez** [comment]
This is not a picture, but might be useful:
![teo](https://user-images.githubusercontent.com/1451819/36475782-161529ae-16fc-11e8-8b0f-cc8255a7af8b.png)

**Comment by jmgarciah** [comment]
Something like @David-Estevez shows could be perfect

**Comment by David-Estevez** [comment]
I can pose it and change the colors to whatever suits your diagrams, just tell me!

**Comment by rsantos88** [comment]
@David-Estevez totally agree :+1:

**Comment by jmgarciah** [comment]
@smcdiaz and me have finished to correct the saggital joint direction. But we have to check that everything is ok

**Comment by rsantos88** [comment]
> @smcdiaz and me have finished to correct the saggital joint direction. But we have to check that everything is ok

I've checked the result with @jmgarciah and it's not working well. 
When I run `launchLocomotion` and check the value of sagital axis, the value is `-3.93673706054688`
I move this axis to homing position, setting position to 0, and the axis moves outside and when I get the position, it returns `-7.45166015625`
@jmgarciah propouse to @jgvictores or @smcdiaz to have a look at this problem because
he has no idea.

**Comment by rsantos88** [comment]
Changed sign of CUI Absolute Encoder to read the correct joint directions of rotation.
See [here](https://github.com/roboticslab-uc3m/teo-configuration-files/pull/8) the changes. It has been tested and it works ok. Now the directions of rotation of the joint ID 5 and 12 correspond to the diagram.

Note: the axial rotation of the waist has not been corrected

**Comment by rsantos88** [comment]
notes: 
* [PR](https://github.com/roboticslab-uc3m/teo-configuration-files/pull/8) is pending to be performed, but it has been changed on the robot to be use.
* After all the changes, I've corrected the home position of the legs (more accurate initial position)

**Comment by rsantos88** [comment]
Other curious note observed: 
* When you run `launchLocomotion`, always the right sagittal leg moves arround 10º degrees out.
You can correct this doing the home position with `--homePoss`, but something causes the joint to move when the driver is initializing.

**Comment by jmgarciah** [comment]
The legs' sagittal joints are already fixed. The only remaining joint is the axial waist. Fixing via hardware this joint is more complicate than via software, I think. It is neccesary to separe the body from the legs. I propose to change the values from .ini files. Please @jgvictores , help us.

**Comment by jgvictores** [comment]
On my way!

**Comment by jgvictores** [comment]
> It is neccesary to separe the body from the legs. I propose to change the values from .ini files

First diagrams, then update all related configuration files and robot models.

**Comment by jgvictores** [comment]
The fact that there are negative `trs` in `launchLocomotion.ini` means that diagrams are incorrect.
I've opened https://github.com/roboticslab-uc3m/teo-configuration-files/issues/11 pointing at the situation.

**Comment by rsantos88** [comment]
> The fact that there are negative trs in launchLocomotion.ini means that diagrams are incorrect.
> I've opened roboticslab-uc3m/teo-configuration-files#11 pointing at the situation.

https://github.com/roboticslab-uc3m/teo-configuration-files/issues/11 has been closed.

**Comment by rsantos88** [comment]
The direction of rotation of the axial waist is opposite in the `.ini` config file and the diagram.
What we should to change? The diagram? The config file? or it doesn't matter which of them?

**Comment by jgvictores** [comment]
Better change the .ini (diagrams also affect DH etc)

**Comment by rsantos88** [comment]
Ok, I'm going to work on this issue:
I will use the rotation diagram as a reference, correcting those that have a negative direction and applying the change to the maximum and minimum limits:

![20190225_121930](https://user-images.githubusercontent.com/15872457/53334669-c256ee80-38f9-11e9-8aa7-87b4bb28ee5c.jpg)

I will use the example of the right elbow that @jgvictores  told me:

![juan](https://user-images.githubusercontent.com/15872457/53334824-2e395700-38fa-11e9-8e64-9a647a74e791.jpg)

The result, taking into account the current limits of manipulation and locomotion would be [this](https://github.com/roboticslab-uc3m/teo-configuration-files/commit/5addf18fbf8fb467ca46c082a22920406c2d7f8c).

In my humble opinion, I think it would be quite interesting to reconsider the revision of the limits. In the arms a more detailed revision of the limits has already been made, correcting some errors. (https://github.com/roboticslab-uc3m/teo-main/issues/15#issuecomment-461091935)
I would work on these limits. Also, I would recommend checking the limits of the legs again with @jmgarciah , and apply the new changes of direction. I await your proposals :)

**Comment by jgvictores** [comment]
@rsantos88 I've taken a look at https://github.com/roboticslab-uc3m/teo-configuration-files/commit/5addf18fbf8fb467ca46c082a22920406c2d7f8c and it seems amazing!

-To close this issue I'd be satisfied with real TEO's ini files and manual images, and open separate issues on simulation model repositories
- Note to self: develop small script to enable porting programs to be compatible with new criteria

Issues that will be unblocked:
- Joint limits: see my comment at https://github.com/roboticslab-uc3m/teo-main/issues/15#issuecomment-467021993
- Kinematic model and diagrams: https://github.com/roboticslab-uc3m/teo-main/issues/38
- Probably many more!

**Comment by rsantos88** [comment]
> To close this issue I'd be satisfied with real TEO's ini files and manual images, and open separate issues on simulation model repositories

I've modified the images of directions. Review it please: https://github.com/roboticslab-uc3m/teo-developer-manual/commit/6238c4bc0d75b93c2e416fc87071aecf7e94cf61

> In my humble opinion, I think it would be quite interesting to reconsider the revision of the limits. In the arms a more detailed revision of the limits has already been made, correcting some errors. (https://github.com/roboticslab-uc3m/teo-main/issues/15#issuecomment-461091935)
I would work on these limits. Also, I would recommend checking the limits of the legs again with @jmgarciah , and apply the new changes of direction. I await your proposals :)

To continue with this issue, once again, I would recommend modifying and correcting the limits of the arms and legs and then the direction of rotation, are you agree with that?

**Comment by jgvictores** [comment]
Looks great to me!

IMHO, you can close the issue, and we can proceed with:
- [ ] https://github.com/roboticslab-uc3m/teo-main/issues/15 (joint limits)
- [ ] Update simulated models (must put issue per repo)
- [ ] Update demos (must put issue per repo)
   - https://github.com/roboticslab-uc3m/waiter
   - https://github.com/roboticslab-uc3m/follow-me
   - https://github.com/roboticslab-uc3m/teo-self-presentation

**Comment by rsantos88** [comment]
Here are the result of merging the new **joint limits of arms** with the new **direction of rotation** in "teo-configuration-files" repository: https://github.com/roboticslab-uc3m/teo-configuration-files/pull/18 
(please, check it in case something has escaped me)

Maybe we can keep it this way, without revising the limits of the legs again and consider that the previous measurement with @AlvaroMartinezR  was correct. What do you think? Would it be interesting to review the limits of the legs again before continuing?
If we continue without legs revision, the next steps would be:
- [ ] Accept this pull request
- [ ] Reflect the changes in the tables of **teo-developer-manual** repository

and...
>- [ ] Update simulated models (must put issue per repo)
>- [ ] Update demos (must put issue per repo)
>   - https://github.com/roboticslab-uc3m/waiter
>   - https://github.com/roboticslab-uc3m/follow-me
>   - https://github.com/roboticslab-uc3m/teo-self-presentation

**Comment by jmgarciah** [comment]
I think you should check the whole robot, not just the arms. If we are going to modify the directions of the joints, we should not leave the work halfway.

**Comment by rsantos88** [comment]
Updated: https://github.com/roboticslab-uc3m/teo-main/issues/39#issuecomment-474334416

**Comment by jgvictores** [comment]
> * [x]  Accept pull request (`tr`s in `yarp-devices`): [roboticslab-uc3m/yarp-devices#205](https://github.com/roboticslab-uc3m/yarp-devices/pull/205)

Merged at https://github.com/roboticslab-uc3m/yarp-devices/commit/304b2455538479d21e2ecfc77678e596f359353d

**Comment by jgvictores** [comment]
> * [x]  Accept pull request: [roboticslab-uc3m/teo-developer-manual#50](https://github.com/roboticslab-uc3m/teo-developer-manual/pull/50)

Merged at https://github.com/roboticslab-uc3m/teo-developer-manual/commit/118f4725c86472dc1c8c3782cdde3d49856c6f74

**Comment by jgvictores** [comment]
> * [ ]  Accept this pull request: [roboticslab-uc3m/teo-configuration-files#18](https://github.com/roboticslab-uc3m/teo-configuration-files/pull/18)

Merged at https://github.com/roboticslab-uc3m/teo-configuration-files/commit/23703e1e29182a43c491efe04d4f5a9427d6008a

**Comment by jgvictores** [comment]
> [x] Update demos (or put issue per repo)
> * https://github.com/roboticslab-uc3m/waiter
> * https://github.com/roboticslab-uc3m/follow-me
> * https://github.com/roboticslab-uc3m/teo-self-presentation

Will be tracked at:
- https://github.com/roboticslab-uc3m/waiter/issues/9
- https://github.com/roboticslab-uc3m/follow-me/issues/46
- https://github.com/roboticslab-uc3m/teo-self-presentation/issues/8

**Comment by rsantos88** [comment]
Updated https://github.com/roboticslab-uc3m/teo-main/issues/39#issuecomment-474334416 about **update simulated models**

**Comment by jgvictores** [comment]
> [x] Update simulated models (or put issue per repo)

- https://github.com/roboticslab-uc3m/teo-openrave-models/issues/26 (https://github.com/roboticslab-uc3m/teo-openrave-models/pull/25)
- https://github.com/roboticslab-uc3m/teo-simox-models/issues/3
- https://github.com/roboticslab-uc3m/teo_robot/issues/1
- https://github.com/roboticslab-uc3m/teo-gazebo/issues/5

**Comment by rsantos88** [comment]
Ok! Can I close this issue or do you want to add more things like the change in kinematics (important issue)?

**Comment by jgvictores** [comment]
Yes, please close, and we can actually unblock kinematics! Other issues are all tracked individually. :tada::tada::tada:
